apiVersion: v1
kind: Service
metadata:
  labels:
    app: express-app
  name: express-app
spec:
  ports:
  - port: 3000
    protocol: TCP
    targetPort: 3000
  selector:
    app: express-app
status:
  loadBalancer: {}
